source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-default-layout"
gem "jekyll-seo-tag"
gem "jekyll-github-metadata"
gem "jekyll-include-cache"
gem "jekyll-sitemap"
gem "webrick", "~> 1.7"
